name: Azure CLI Login Tests
on:
  push:
      branches:
        - master
jobs:

  build:
    runs-on: self-hosted
    steps:  
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 
        
    - name: Start VMs every weekday at 7am
      if: github.event.schedule == '0 7 * * 1-5'
      uses: Azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          az vm start --ids $(az vm list -g ${{ env.RG_NAME }} --query "[?tags.keepAlive != 'true'].id" -o tsv)
                  
      # Deallocate VMs every weekday at 6pm
    - name: Deallocate VMs every weekday at 6pm
      if: github.event.schedule == '0 18 * * 1-5'
      uses: Azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          az vm deallocate --ids $(az vm list -g ${{ env.RG_NAME }} --query "[?tags.keepAlive != 'true'].id" -o tsv)
